### ISSUE TITLE
Ueberzug support

### ISSUE THREAD

**Issue by TheHellBox** [atanunq/viuer#13]
Most of the terminals don't support kitty and iTerm protocols. For this reason, many applications(Including [ranger](https://github.com/ranger/ranger/wiki/Image-Previews)) use [ueberzug](https://github.com/seebye/ueberzug) as a way to draw images into the terminal. While this way of displaying images is a bit hacky, it allows us to display full-color full resolution images in almost every common terminal emulator.

**Comment by atanunq** [comment]
That's pretty cool. Initially my goal was to stick with terminals as much as possible and not involve the graphical environment around them. Now when I tested ueberzug I am having second thoughts...

**Comment by TheHellBox** [comment]
Yeah it's cool.
However, after playing with it for a bit in my app, I don't think it suits this library well.
It allows you to draw images on terminal, but it requires you to keep child process opened while doing so, which doesn't suit image printing this library aims for
