### ISSUE TITLE
Better detection of OSC 1337 support

### ISSUE THREAD

**Issue by kidonng** [atanunq/viuer#26]
Currently viuer dumbly [checks `iTerm` in `TERM_PROGRAM`](https://github.com/atanunq/viuer/blob/a9e638cce13f1012bc64e6ce33a848ac461675c3/src/printer/iterm.rs#L87-L95). However there are a handful of terminal emulators that support the OSC 1337 escape codes, i.e. iTerm2's image protocols:

- [iTerm2](https://iterm2.com/documentation-images.html) (of course)
- [mintty](https://github.com/mintty/mintty/wiki/CtrlSeqs#image-support)
- [WezTerm](https://wezfurlong.org/wezterm/imgcat.html)
- [MacTerm](https://www.macterm.net/)
- [SwiftTerm](https://github.com/migueldeicaza/SwiftTerm)
- [Mlterm](https://sourceforge.net/p/mlterm/mailman/message/34931431/)
- [hterm](https://chromium.googlesource.com/apps/libapps/+/master/nassh/doc/FAQ.md#How-do-I-view-images) (though this one runs on Chromium OS/web, so probably viu doesn't need to care about it now)

There should be a better method of checking support of the protocol.

A workaround is just to [fake iTerm to viuer](https://github.com/atanunq/viu/issues/72#issuecomment-833982679).

**Comment by atanunq** [comment]
The list is really helpful, thank you! I am struggling to find information about `SwiftTerm` and `MacTerm`, though. Do they set either `$TERM` or `$TERM_PROGRAM`?

`Mlterm` & `hterm` look pretty niche to me, I'd rather not include them unless specifically requested.

**Comment by atanunq** [comment]
Added only the first two in https://github.com/atanunq/viuer/commit/42cd38c61b8ab007922f559056d10ee69a86f737
