### ISSUE TITLE
too many files under /tmp

### ISSUE THREAD

**Issue by tramhao** [atanunq/viuer#47]
I'm using viuer to display album cover. One use met a problem though, as in
https://github.com/tramhao/termusic/issues/92 .
Would you please check if it's I'm using viuer wrong or you need to fix in upstream? Thanks so much.

**Comment by tramhao** [comment]
Is this repo still maintained? Thanks.

Another user met the problem and found a way to reproduce it: https://github.com/tramhao/termusic/issues/122

**Comment by atanunq** [comment]
Fixed in https://github.com/atanunq/viuer/pull/51
