### ISSUE TITLE
Is this crate maintained?

### ISSUE THREAD

**Issue by virtualritz** [atanunq/viuer#60]
See subject. :grin:

**Comment by atanunq** [comment]
I would like to think so :)

I greatly appreciate people's effort into opening PRs. Will do my best to review them over the next several days.

**Comment by virtualritz** [comment]
Awesome, thank you so much! :smiley: 

I just prefer using a publised crate rather than an overlay. 

We're using `viuer` to display test results from our [`openimageio` wrapper](https://github.com/phyrondev/openimageio) in the terminal for visual feedback.
